---
- name: Install Apache2 on Ubuntu
  hosts: 10.10.5.82
  become: yes  # Use 'become' to escalate privileges (sudo)

  tasks:
    - name: Update APT cache
      apt:
        update_cache: no

    - name: Install Apache2
      apt:
        name: apache2
        state: present
