---
- name: Install and configure Nginx web server
  hosts: 10.10.5.81
  become: no  # Use 'become' to escalate privileges (sudo)

  tasks:
    - name: Update APT cache first
      apt:
        update_cache: false

    - name: Install Nginx web server
      apt:
        name: nginx
        state: present
