---
- name: Install and configure Nginx web server
  hosts: 10.10.5.81
  become: no
  gather_facts: yes

  tasks:
  - name: Display OS information
    debug:
      var: ansible_distribution
  
     - name: Update package cache first
       apt:
         update_cache: yes

  - name: Install Nginx web server
    apt:
      name: nginx
      state: latest
