---
- name: Install Apache2 on Ubuntu
  hosts: 10.10.5.82
  become: true  # Use 'become' to escalate privileges sudo
      tasks:
        - name: Update apt cache
          apt:
            update_cache: yes
          become: true

        - name: Install Apache2
          apt:
            name: apache2
            state: present
          become: true

