---
- name: Install Prometheus on Ubuntu
  hosts: 172.16.0.246
  become: yes  # Use 'become' to escalate privileges (sudo)

  tasks:
    - name: Add Prometheus APT repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        filename: 'grafana'

    - name: Add GPG key for Prometheus APT repository
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Update APT cache first
      apt:
        update_cache: false

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
